### ISSUE TITLE
JWT Unit 테스트 코드 작성

### ISSUE THREAD

**Issue by kyeonkim** [kyeonkim/backend-develop-onboarding-project#1]
# ToDo

- [x] JWT token 생성 기능 추가
- [x] JWT token 검증 기능 추가
- [x]  JUnit를 이용한 JWT Unit 테스트 코드 작성해보기

# 참고
- https://preasim.github.io/39  
- [[https://velog.io/@da_na/Spring-Security-JWT-Spring-Security-Controller-Unit-Test하기](https://velog.io/@da_na/Spring-Security-JWT-Spring-Security-Controller-Unit-Test%ED%95%98%EA%B8%B0)](https://velog.io/@da_na/Spring-Security-JWT-Spring-Security-Controller-Unit-Test%ED%95%98%EA%B8%B0)
