### ISSUE TITLE
AWS EC2에 배포 진행

### ISSUE THREAD

**Issue by kyeonkim** [kyeonkim/backend-develop-onboarding-project#4]
# ToDo

- [x] AWS EC2에 배포 진행
- [x] /signup, /sign api 테스트 진행

# 테스트 결과
- [x] 배포가 정상적으로 되었는가?
- [x] 배포 환경에서 회원가입이 정상적으로 되는가? 
![image](https://github.com/user-attachments/assets/ea304717-7eb7-4af1-9e8c-70ad9ad608f4)
- [x] 배포 환경에서 로그인 시 acess, refresh token이 정상적으로 발급되었는가?
![image](https://github.com/user-attachments/assets/e51b633e-cff1-4ecb-b5d5-a7024b2af163)
