### ISSUE TITLE
AI를 통한 코드리뷰 기능 추가

### ISSUE THREAD

**Issue by kyeonkim** [kyeonkim/backend-develop-onboarding-project#6]
# ToDo

- [x] 커밋 시 실행되는 코드리뷰 AI 추가
- [x] AI의 피드백을 통해 코드 개선하기
- [x] 개선된 코드를 AWS EC2에 재배포
